import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve,join } from 'node:path';
import { chromium } from 'playwright-core';
import { createServer } from 'vite';
import { runtime, uid, wait, sleep } from './support/combat-runtime.mjs';
const h=await runtime(),artifacts=resolve('dist/combat-checks');await mkdir(artifacts,{recursive:true});let browser,server;const contexts=[],errors=[];let passes=0;const pass=s=>console.log(`PASS ${++passes}: ${s}`);
async function page(width,height=900,reduced=false,fallback=false,clockSkew=0){const ctx=await browser.newContext({viewport:{width,height},reducedMotion:reduced?'reduce':'no-preference'});contexts.push(ctx);await ctx.addInitScript(({fallback,clockSkew})=>{const Native=window.WebSocket;window.__combatSockets=[];window.__combatMessages=[];window.__combatIntents=[];window.WebSocket=class extends Native{constructor(...args){super(...args);window.__combatSockets.push(this);this.addEventListener('message',event=>{if(event.data!=='pong')window.__combatMessages.push(JSON.parse(event.data));});}send(data){if(data!=='ping')window.__combatIntents.push(JSON.parse(data));super.send(data);}};if(fallback)HTMLCanvasElement.prototype.getContext=()=>null;const dateNow=Date.now;Date.now=()=>dateNow()+clockSkew;},{fallback,clockSkew});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(String(h.origin));return p;}
const credentials=p=>p.evaluate(()=>JSON.parse(sessionStorage.getItem('mm.room.v2')));
const entry=async p=>({credentials:await credentials(p)});
const view=async p=>h.view(await entry(p));
const edit=async(p,fn)=>h.record((await credentials(p)).roomId,fn);
async function connected(p){await p.waitForFunction(()=>document.querySelector('.connection-badge')?.textContent.includes('Connected')&&document.querySelector('.room-panel'));}
async function create(p){await p.getByLabel('Player Name',{exact:true}).fill('Browser Host');await p.getByRole('button',{name:'Create Private Laboratory',exact:true}).click();await connected(p);return credentials(p);}
async function joinRoom(p,id,name,display=false){await p.getByLabel('Invitation code',{exact:true}).fill(id);if(display)await p.getByLabel('Join as a display without a player seat').check();else await p.getByLabel('Player Name',{exact:true}).fill(name);await p.getByRole('button',{name:'Join by Code',exact:true}).click();await connected(p);}
async function sync(p){const c=await credentials(p),revision=(await view(p)).snapshot.revision;await p.evaluate(({revision})=>window.__combatSockets.at(-1).send(JSON.stringify({protocolVersion:5,actionId:crypto.randomUUID(),kind:'sync-request',afterRevision:revision})),{revision});await p.waitForFunction(revision=>window.__combatMessages.some(m=>m.kind==='room-snapshot'&&m.snapshot.revision>=revision),revision);await p.waitForFunction(revision=>window.__combatMessages.some(m=>m.kind==='controller-snapshot'&&m.snapshot.revision>=revision),revision);}
async function expire(p){const c=await credentials(p);await h.record(c.roomId,r=>{const next=Date.now()-1;if(r.phase==='battle'){const shift=next-r.phaseDeadlineMs;r.combat.battle.timeline.startsAtMs+=shift;r.combat.battle.result.completedAtMs+=shift;}r.phaseDeadlineMs=next;});return view(p);}
async function inject(p,dnaId){const c=await credentials(p);await edit(p,r=>{const seat=r.seats.find(s=>s.id===c.sessionId);seat.tray[0].dnaId=dnaId;seat.nextInjectionAtMs=0;});await sync(p);await p.waitForFunction(()=>document.querySelectorAll('.specimen-button').length===4&&![...document.querySelectorAll('.specimen-button')].some(b=>b.disabled));const previous=(await view(p)).controller.remainingDoses;await p.locator('.specimen-button').first().click();await p.getByRole('button',{name:'Inject selected specimen',exact:true}).click();await wait(()=>view(p),v=>v.controller.remainingDoses===previous-1);await p.waitForFunction(()=>sessionStorage.getItem('mm.pending-intent.v5')===null);}
async function a11y(p,label){await p.addScriptTag({path:resolve('node_modules/axe-core/axe.min.js')});const issues=await p.evaluate(async()=>{const report=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return report.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});assert.deepEqual(issues,[],label);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${label} overflow`);}
try{
 browser=await chromium.launch({executablePath:process.env.MM_CHROME_PATH??'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});
 const desktop=await page(1280),phone=await page(390,844,true,false,120000),display=await page(1920,1080,false,true);
 const c=await create(desktop);await joinRoom(phone,c.roomId,'Phone Scientist');await joinRoom(display,c.roomId,'',true);
 await desktop.getByRole('button',{name:'Start experiment',exact:true}).click();await desktop.getByLabel('Rival briefing',{exact:true}).waitFor();await a11y(desktop,'briefing');await desktop.screenshot({path:join(artifacts,'briefing-desktop.png'),fullPage:true});
 await expire(desktop);await wait(()=>view(desktop),v=>v.snapshot.phase==='experiment');
 for(const id of ['razor-talons','guillotine-teeth','auxiliary-heart','spring-tendons','ossified-plates','hook-tentacles'])await inject(desktop,id);
 await inject(phone,'all-seeing-cluster');await desktop.waitForFunction(()=>!document.querySelector('.unleash-switch').disabled);await desktop.getByRole('button',{name:'Unleash the Creature!',exact:true}).click();await phone.waitForFunction(()=>!document.querySelector('.unleash-switch').disabled);await phone.getByRole('button',{name:'Unleash the Creature!',exact:true}).click();
 await desktop.getByRole('heading',{name:'Creature released. Prepare for combat!',exact:true}).waitFor();await desktop.getByLabel('Automatic battle',{exact:true}).waitFor();await phone.getByLabel('Automatic battle',{exact:true}).waitFor();await display.getByLabel('Automatic battle',{exact:true}).waitFor();
 const timeline=(await view(desktop)).snapshot.battle;assert.ok(timeline.events.length);assert.deepEqual((await view(phone)).snapshot.battle,timeline);assert.deepEqual((await view(display)).snapshot.battle,timeline);
 const meter=p=>p.locator('.battle-health meter').evaluateAll(ms=>ms.map(m=>m.value));await wait(async()=>{const values=await Promise.all([meter(desktop),meter(phone),meter(display)]);return values.every(v=>JSON.stringify(v)===JSON.stringify(values[0]));},Boolean);
 assert.equal(await phone.locator('.battle-still').count(),1);assert.equal(await display.getByRole('button',{name:'Next experiment',exact:true}).count(),0);assert.equal(await desktop.locator('.chamber-canvas canvas').count(),1);
 for(const [p,label] of [[desktop,'battle-desktop'],[phone,'battle-phone-portrait'],[display,'battle-display-static']]){await a11y(p,label);await p.screenshot({path:join(artifacts,`${label}.png`),fullPage:true});}
 const sockets=await phone.evaluate(()=>window.__combatSockets.length);await phone.setViewportSize({width:844,height:390});await a11y(phone,'phone landscape');await phone.screenshot({path:join(artifacts,'battle-phone-landscape.png'),fullPage:true});assert.equal(await phone.evaluate(()=>window.__combatSockets.length),sockets);
 pass('real browser injections/switches reach the same battle; desktop, phone portrait/landscape, skewed clock, reduced motion and display fallback pass');
 await phone.reload();await connected(phone);await phone.getByLabel('Automatic battle',{exact:true}).waitFor();assert.ok(Number(await phone.locator('.battle-stage').getAttribute('data-elapsed'))>1000);assert.deepEqual((await view(phone)).snapshot.battle,timeline);assert.equal(await phone.locator('.battle-captions li').count()<=3,true);
 pass('battle reload restores credentials and seeks current health/anatomy with a bounded caption window');
 const expected=(await h.record(c.roomId)).combat.battle.result;await expire(desktop);await desktop.getByLabel('Authoritative results',{exact:true}).waitFor();await phone.getByLabel('Authoritative results',{exact:true}).waitFor();assert.equal((await view(desktop)).snapshot.result.outcome,expected.outcome);assert.equal(await phone.getByRole('button',{name:'Next experiment',exact:true}).count(),0);await a11y(desktop,'autopsy');await desktop.screenshot({path:join(artifacts,'autopsy-desktop.png'),fullPage:true});
 await desktop.getByRole('button',{name:'Next experiment',exact:true}).focus();await desktop.keyboard.press('Enter');await desktop.getByLabel('Rival briefing',{exact:true}).waitFor();assert.equal((await view(desktop)).snapshot.round,2);
 for(let round=2;round<=3;round++){await expire(desktop);await expire(desktop);await expire(desktop);await desktop.getByLabel('Automatic battle',{exact:true}).waitFor();await expire(desktop);await desktop.getByLabel('Authoritative results',{exact:true}).waitFor();if(round===2){await desktop.getByRole('button',{name:'Next experiment',exact:true}).click();await desktop.getByLabel('Rival briefing',{exact:true}).waitFor();}}
 const session=(await view(desktop)).snapshot;assert.equal(session.phase,'session-results');assert.equal(session.session.completed.length,3);await a11y(phone,'session results');await desktop.screenshot({path:join(artifacts,'session-results.png'),fullPage:true});assert.equal(await phone.getByRole('button',{name:'Play Again',exact:true}).count(),0);await desktop.getByRole('button',{name:'Play Again',exact:true}).click();await desktop.getByLabel('Rival briefing',{exact:true}).waitFor();assert.equal((await view(desktop)).snapshot.teamScore,0);
 pass('real keyboard/mouse host progression, revealed autopsy/commendations, session totals and replay work without player/display host controls');
 server=await createServer({server:{host:'127.0.0.1',port:0}});await server.listen();const origin=server.resolvedUrls.local[0],gallery=await browser.newPage({viewport:{width:1200,height:1000}});gallery.on('pageerror',e=>errors.push(e.message));await gallery.goto(new URL('/combat-gallery',origin).href);await gallery.getByRole('heading',{name:'Combat artwork study',exact:true}).waitFor();
 for(let i=0;i<6;i++){await gallery.getByLabel('Rival study',{exact:true}).selectOption(String(i));await gallery.getByLabel('Battle time',{exact:true}).evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'8000');el.dispatchEvent(new Event('input',{bubbles:true}));});await gallery.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await a11y(gallery,`rival ${i}`);await gallery.screenshot({path:join(artifacts,`rival-${i+1}.png`),fullPage:true});}
 await gallery.getByLabel('Rival study',{exact:true}).selectOption('1');await gallery.getByLabel('Battle time',{exact:true}).evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'18000');el.dispatchEvent(new Event('input',{bubbles:true}));});await gallery.screenshot({path:join(artifacts,'detached-anatomy.png'),fullPage:true});
 pass('six authored rivals and actual modular anatomy render in the reproducible Vite-only combat gallery');
 const fixtures=JSON.parse(await readFile('src/assets/combat-fixtures.json','utf8')),impact=fixtures[0].timeline.events.find(e=>['attack','electric'].includes(e.kind)&&e.magnitude>=10);
 assert.ok(impact);await gallery.getByLabel('Rival study',{exact:true}).selectOption('0');await gallery.getByLabel('Event motion',{exact:true}).check();
 await gallery.getByLabel('Battle time',{exact:true}).evaluate((el,time)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,String(time));el.dispatchEvent(new Event('input',{bubbles:true}));},impact.offsetMs);
 await gallery.waitForFunction(()=>document.querySelector('.battle-arena').dataset.camera==='impact');await gallery.waitForFunction(()=>getComputedStyle(document.querySelector('.battle-camera')).transform!=='none');
 await gallery.emulateMedia({reducedMotion:'reduce'});await gallery.waitForFunction(()=>getComputedStyle(document.querySelector('.battle-camera')).transform==='none');
 await gallery.emulateMedia({reducedMotion:'no-preference'});await gallery.getByLabel('Event motion',{exact:true}).uncheck();await gallery.waitForFunction(()=>getComputedStyle(document.querySelector('.battle-camera')).transform==='none');
 pass('an authoritative heavy-impact frame moves the camera; reduced and paused motion keep the camera still');
 const failure=await browser.newPage({viewport:{width:390,height:844}});failure.on('pageerror',e=>errors.push(e.message));
 await failure.route('**/assets/rivals/*.webp',route=>route.abort());await failure.route('**/assets/laboratory/creature.blob.webp',route=>route.abort());
 await failure.goto(new URL('/combat-gallery',origin).href);
 await failure.getByRole('button',{name:'Retry rival artwork',exact:true}).waitFor();await failure.getByRole('button',{name:'Retry creature artwork',exact:true}).waitFor();
 const failureBattle=await failure.locator('.battle-stage').getAttribute('data-battle-id'),failureHealth=await failure.locator('meter').evaluateAll(elements=>elements.map(e=>e.value));
 await a11y(failure,'failed battle artwork');await failure.unrouteAll();await failure.getByRole('button',{name:'Retry rival artwork',exact:true}).click();await failure.getByRole('button',{name:'Retry creature artwork',exact:true}).click();
 await failure.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));
 assert.equal(await failure.getByRole('button',{name:'Retry rival artwork',exact:true}).count(),0);assert.equal(await failure.getByRole('button',{name:'Retry creature artwork',exact:true}).count(),0);
 assert.equal(await failure.locator('.battle-stage').getAttribute('data-battle-id'),failureBattle);assert.deepEqual(await failure.locator('meter').evaluateAll(elements=>elements.map(e=>e.value)),failureHealth);await failure.close();
 pass('failed rival and modular SVG art retain accessible health and recover through real retry controls without changing the battle');
 assert.deepEqual(errors,[]);console.log(`Completed ${passes} combat browser scenarios. Screenshots: ${artifacts}. Headless Chrome viewport emulation is not physical-device verification.`);
}finally{await server?.close();for(const ctx of contexts)await ctx.close();await browser?.close();await h.close();}
