import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createServer } from 'vite';
import { chromium } from 'playwright-core';
import sharp from 'sharp';
const phase=process.argv[2]??'after';
const output=resolve(`dist/composition-review/${phase}`);await mkdir(output,{recursive:true});
const reference=JSON.parse(await readFile('src/assets/reference-compositions.json','utf8'));
const fixtures=JSON.parse(await readFile('src/assets/composition-fixtures.json','utf8'));
const server=await createServer({server:{host:'127.0.0.1',port:0}});let browser;
const errors=[];
// Layer order is intentional, so compare sets rather than received ordering.
async function ready(page,f,staticMode=false){await page.getByLabel('Review composition',{exact:true}).selectOption(f.id);await page.waitForFunction(({keys,staticMode})=>{if(staticMode)return document.querySelector('.static-creature')&&[...document.querySelectorAll('.static-creature img')].every(i=>i.complete&&i.naturalWidth)&&document.querySelectorAll('.static-creature img').length===keys.length;const host=document.querySelector('.chamber-canvas');return host?.dataset.composition?.split(',').sort().join(',')===keys.sort().join(',')&&!document.querySelector('.art-notice');},{keys:f.creature.parts.map(p=>p.instanceId),staticMode});}
async function thumbnail(file){const m=await sharp(file).metadata();return sharp(file).extract({left:Math.floor(m.width*.1776),top:Math.floor(m.height*.1466),width:Math.floor(m.width*.6564),height:Math.floor(m.height*.6046)}).resize(288,398,{fit:'contain',background:'#171e18'}).png().toBuffer();}
async function sheet(records,path,columns=4){const width=300,height=450;const tiles=[];for(const[i,r]of records.entries()){const x=i%columns*width,y=Math.floor(i/columns)*height;tiles.push({input:await thumbnail(r.file),left:x+6,top:y+4});const label=r.label.replaceAll('&','&amp;').replaceAll('<','&lt;');tiles.push({input:Buffer.from(`<svg width="300" height="40"><text x="8" y="24" fill="#eee5ca" font-family="sans-serif" font-size="12">${label}</text></svg>`),left:x,top:y+406});}await sharp({create:{width:columns*width,height:Math.ceil(records.length/columns)*height,channels:4,background:'#171e18'}}).composite(tiles).png().toFile(path);}
if(process.argv.includes('--sheets-only')){await sheet(fixtures.filter(f=>!f.id.startsWith('single-')).map(f=>({file:`${output}/${f.id}.png`,label:f.label})),`${output}/contact-sheet.png`);await sheet(fixtures.filter(f=>f.id.startsWith('single-')).map(f=>({file:`${output}/${f.id}.png`,label:f.label})),`${output}/all-30-modules.png`,5);await server.close();process.exit(0);}
try{await server.listen();browser=await chromium.launch({executablePath:process.env.MM_CHROME_PATH??'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const origin=server.resolvedUrls.local[0];
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:2,reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));await page.goto(new URL('/art-gallery',origin).href);await ready(page,fixtures[0]);
const representative=[];const individual=[];
for(const f of [...fixtures,...reference]){await ready(page,f);assert.ok(Number(await page.locator('.chamber-canvas').getAttribute('data-texture-count'))<=16);const file=`${output}/${f.id}.png`;await page.locator('.chamber-stage').screenshot({path:file});(f.id.startsWith('single-')?individual:representative).push({file,label:f.label});}
await sheet(representative.filter(r=>!r.label.startsWith('SJM ')),`${output}/contact-sheet.png`);await sheet(individual,`${output}/all-30-modules.png`,5);await sheet(representative.filter(r=>r.label.startsWith('SJM ')),`${output}/definitive-contact-sheet.png`);
const heavy=fixtures.find(f=>f.id==='reinforced');
await ready(page,heavy);await page.locator('.chamber-stage').screenshot({path:`${output}/reduced-motion.png`});
for(const[id,viewport,display]of [['phone-portrait',{width:390,height:844},false],['phone-landscape',{width:844,height:390},false],['display',{width:1920,height:1080},true]]){await page.setViewportSize(viewport);await page.locator('main').evaluate((e,d)=>e.classList.toggle('display-layout',d),display);await ready(page,heavy);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${output}/${id}.png`,fullPage:true});}
await page.setViewportSize({width:1440,height:1100});await page.locator('main').evaluate(e=>e.classList.remove('display-layout'));await page.getByRole('button',{name:'Animate preview',exact:true}).click();await ready(page,heavy);await page.locator('.chamber-stage').screenshot({path:`${output}/animated.png`});await page.close();
const staticPage=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:2,reducedMotion:'reduce'});staticPage.on('pageerror',e=>errors.push(e.message));await staticPage.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=()=>null;});await staticPage.goto(new URL('/art-gallery',origin).href);await ready(staticPage,heavy,true);await staticPage.getByText('static graphics fallback',{exact:false}).waitFor();await staticPage.locator('.chamber-stage').screenshot({path:`${output}/static.png`});
if(phase!=='before'){
 const a=await sharp(`${output}/reduced-motion.png`).removeAlpha().raw().toBuffer();const b=await sharp(`${output}/static.png`).removeAlpha().raw().toBuffer();assert.equal(a.length,b.length);const mean=a.reduce((sum,v,i)=>sum+Math.abs(v-b[i]),0)/a.length;assert.ok(mean<3,`Animated/static stable-pose mean pixel difference ${mean}`);console.log(`Stable-pose canvas/static mean channel difference: ${mean.toFixed(3)} / 255`);
 const bounds=await staticPage.evaluate(async()=>{const {creatureLayers,layerBounds}=await import('/src/client/creature-render.ts');const fixtures=(await import('/src/assets/composition-fixtures.json')).default;const layers=creatureLayers(fixtures.find(f=>f.id==='reinforced').creature).layers;const frame=document.querySelector('.static-creature').getBoundingClientRect();return [...document.querySelectorAll('.static-creature img')].map((img,i)=>{const rect=img.getBoundingClientRect(),l=layerBounds(layers[i]);return{dx:Math.abs(rect.left-(frame.left+l.left/600*frame.width)),dy:Math.abs(rect.top-(frame.top+l.top/720*frame.height)),dw:Math.abs(rect.width-l.width/600*frame.width)};});});assert.ok(bounds.every(b=>b.dx<.1&&b.dy<.1&&b.dw<.1));
 let worst=0;
 for(const f of reference){await ready(staticPage,f,true);const file=`${output}/${f.id}-static.png`;await staticPage.locator('.chamber-stage').screenshot({path:file});const canvas=await sharp(`${output}/${f.id}.png`).removeAlpha().raw().toBuffer(),fallback=await sharp(file).removeAlpha().raw().toBuffer();assert.equal(canvas.length,fallback.length);const difference=canvas.reduce((sum,v,i)=>sum+Math.abs(v-fallback[i]),0)/canvas.length;assert.ok(difference<3,`${f.id} canvas/static difference ${difference}`);worst=Math.max(worst,difference);}
 console.log(`All 12 definitive-sheet static/animated comparisons passed; worst mean channel difference ${worst.toFixed(3)} / 255`);
 await ready(staticPage,heavy,true);
 for(const[id,viewport,display]of [['static-phone',{width:390,height:844},false],['static-display',{width:1920,height:1080},true]]){await staticPage.setViewportSize(viewport);await staticPage.locator('main').evaluate((e,d)=>e.classList.toggle('display-layout',d),display);await ready(staticPage,heavy,true);await staticPage.screenshot({path:`${output}/${id}.png`,fullPage:true});}
}
assert.deepEqual(errors,[]);console.log(`PASS: ${fixtures.length} authoritative compositions, ${reference.length} definitive-sheet art samplers, all 30 modules, desktop/phone portrait/landscape/display, animated/reduced-motion/static. ${output}`);
}finally{await browser?.close();await server.close();}
